# fly.toml app configuration file generated for bookingruangan-iann221 on 2023-05-02T17:26:45+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bookingruangan-iann221"
primary_region = "sin"

[build]
  image = "iann221/bookingruangan:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
