# fly.toml app configuration file generated for bookingruangan-iann221 on 2023-05-03T09:53:47+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bookingruangan-iann221"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "sin"
processes = []

[build]
  image = "iann221/bookingruangan:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
